### ISSUE TITLE
\contacts command does nothing

### ISSUE THREAD

**Issue by J0ySF** [miculan/thud#2]
The `\contacts` command does not appear to alter the document's appearance in any way.

## To Reproduce
Build the document as is.

## Expected behavior
One would expect the `\contacts` command content to appear in the document's in some way.

**Comment by MatteoPaier** [comment]
`\contacts` is intended "Per le sole tesi di dottorato:" ("Only for PhD thesis")
If you compile with `target=phd` the content appears as Author's Contacts below the fixed Institute Contacts in page 2
