### ISSUE TITLE
Elenco delle figure

### ISSUE THREAD

**Issue by Gnooodles** [miculan/thud#3]
## Problema con il comando \listoffigures

**Descrizione del problema:**
Il comando `\listoffigures` causa un problema di gestione delle pagine bianche.

**Dettagli:**
Il file allegato è stato prodotto dal template fornito, scommentando solamente il comando precedentemente citato e rimuovendo ringraziamenti e sommario.

**Allegato:**
[thesis.pdf](https://github.com/miculan/thud/files/15400831/thesis.pdf)

**Passi per riprodurre il problema:**
1. Utilizzare il template fornito.
2. Scommentare il comando `\listoffigures`.
3. Rimuovere i ringraziamenti e il sommario.
4. Compilare il documento.

**Comportamento atteso:**
Il comando `\listoffigures` dovrebbe generare l'elenco delle figure senza causare problemi di pagine bianche e di ordinamento di delle successive.

**Comportamento attuale:**
Il comando `\listoffigures` causa la comparsa di pagine bianche indesiderate.

**Sistema utilizzato:**
- Sistema operativo: macOs 14.5
- Versione di LaTeX: pdfTeX 3.141592653-2.6-1.40.26 (TeX Live 2024)

**Comment by MatteoPaier** [comment]
Prova con questo fix: 649cca14682a117a62fc4bfbd40d8148aa596d5b

Ho testato un po' e pare andare. Se riesci testa anche tu con ToC, LoF e LoT di diverse lungezze (più o meno pagine)

**Comment by Gnooodles** [comment]
Sì, ho testato anche io qualche documento ed è corretto.
Prima di questa soluzione avevo momentaneamente risolto aggiungendo `\usepackage{tocbibind}` nei pacchetti consigliati sotto la voce riguardante il suo commento

**Comment by MatteoPaier** [comment]
Grazie per i test.
Puoi aggiungere in #4 cosa hai provato? I.e. con quante pagine di ToC hai testato e verificato il funzionamento.

Con `tocbibind` funzionava? Allungava il ToC e cambiava il numero di pagine, forse (?)
Il problema pare essere legato in parte alla lunghezza di ToC, LoF e LoT: se l'ultimo tra questi finisce a sinistra viene inserita una pagina vuota che manda anche il primo capitolo a sinistra

**Comment by Gnooodles** [comment]
No non credo fosse per quella motivazione, in quanto il ToC era in entrambi i casi di 1 pagina.

Ho appena provato ad eseguire questi passaggi nel template:
1. Scommentare il comando `\listoffigures`
2. Rimuovere i ringraziamenti e il sommario
3. Inserire `\usepackage{tocbibind}`
4. Compilare il documento.

Ed il risultato è effettivamente corretto: 
[thesis.pdf](https://github.com/miculan/thud/files/15501590/thesis.pdf)
